export const PRODUCTS = [
  {
    id: 1,
    productName: "AXOR Apex Beast Gloss Black Green",
    brand:"axor",
    price: 4999.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2022/03/AXOR-Apex-Beast-Gloss-Black-Green-Full-Face-Helmet3.jpg",
  },
  {
    id: 2,
    productName: "AXOR Apex Beast Gloss Black Grey",
    brand:"axor",
    price: 4999.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2022/03/AXOR-Apex-Beast-Gloss-Black-Grey-Full-Face-Helmet.jpg",
  },
  {
    id: 3,
    productName: "AXOR Apex Hunter Gloss Black Fluorescent Green",
    brand:"axor",
    price: 4999.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2022/06/AXOR-Apex-Hunter-Gloss-Black-Fluorescent-Green-Full-Face-Helmet.webp",
  },
  {
    id: 4,
    productName: "SMK Allterra Fulmine Off-road Gloss Helmet (GL174)",
    brand:"smk",
    price: 5999.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2022/07/SMK-Allterra-Fulmine-Off-road-Gloss-Helmet-_GL174_.webp",
  },
  {
    id: 5,
    productName: "SMK Gullwing Kresto Black Grey Yellow Gloss (GL264) Helmet",
    brand:"smk",
    price: 6499.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2022/04/SMK-Gullwing-Kresto-Black-Grey-Yellow-Gloss-GL264-Helmet.webp",
  },
  {
    id: 6,
    productName: "SMK Phoenix Matt Black (MA2CA) Helmet",
    brand:"smk",
    price: 2999.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2022/03/SMK-Phoenix-Matt-Black-Full-Face-Helmet.jpg",
  },
  {
    id: 7,
    productName: "Royal Enfield AOD White Helmet",
    brand:"re",
    price: 2699.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2022/04/Royal-Enfield-AOD-White-Open-Face-Helmet.webp",
  },
  {
    id: 8,
    productName: "Royal Enfield Jet MLG Open Face Matt Helmet-Desert Storm",
    brand:"re",
    price: 2999.0,
    productImage: "https://www.customelements.in/wp-content/uploads/2023/02/Royal-Enfield-Jet-MLG-Open-Face-Matt-Helmet-Desert-Storm.webp",
  },
];
